name = "gmail-worker"
main = "src/index.mjs"
compatibility_date = "2022-12-20"
compatibility_flags = [ "nodejs_compat_v2" ]

[[kv_namespaces]]
binding = "gmail-worker-kv"
id = "db3ab971d2c749df91e0d3c1d188f702"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[triggers]
crons = [ "*/30 * * * *" ]
